---

AllCops:
  TargetRubyVersion: 2.3
Metrics/BlockLength:
  ExcludedMethods:
    - describe
Security/MarshalLoad:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Metrics/AbcSize:
  Severity: refactor
Metrics/MethodLength:
  Severity: refactor

